In [14]:
import numpy as np
import pandas as pd

df = pd.read_csv('iris.csv')
print(df)

df.drop(columns=['Id'],inplace=True)

#df_train = df.head(100)

#df_test = df.tail(50)




      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X = df.iloc[:,0:4]
Y = df['Species']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)
log_reg = LogisticRegression()
log_reg.fit(X_train,Y_train)
print(log_reg.coef_)
print(log_reg.intercept_)
#y_pred = log_reg.predict(X_test)

[[-0.41449822  0.84920396 -2.33184383 -0.99147821]
 [ 0.521025   -0.29401477 -0.21784701 -0.71159359]
 [-0.10652679 -0.55518919  2.54969084  1.7030718 ]]
[  9.23999169   1.7366026  -10.97659429]


In [28]:
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support as score, accuracy_score

# Assuming you have already defined prediction and Y_test
prediction = log_reg.predict(X_test)

confusion_mat = confusion_matrix(Y_test, prediction)
print(confusion_mat)

precision, recall, fscore, support = score(Y_test, prediction)
print("Precision:", precision)
print("Recall:", recall)
print("F-score:", fscore)
print("Support:", support)

accuracy = accuracy_score(Y_test, prediction)
print("Accuracy:", accuracy)


[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Precision: [1.  1.  0.9]
Recall: [1.     0.9375 1.    ]
F-score: [1.         0.96774194 0.94736842]
Support: [13 16  9]
Accuracy: 0.9736842105263158
